"""
build.py - True single-file standalone bundler using stickytape.

Produces both standalone bundles and terminal wrappers from dev_helper scripts.

Standalone:  Single-file .py that runs on any machine (no install needed). path_args and any local dependencies are
inlined. Variants declared in build_more.py are generated by patching
constants in the original source before bundling.

Terminal:    Thin wrappers for pip-installed users that import dev_helper.*.


Usage:
    python build.py
"""

from __future__ import annotations

import re
import shutil
import tempfile
import textwrap
from pathlib import Path

import stickytape

DEV_HELPER = Path(__file__).parent / "dev_helper"
STANDALONE = Path(__file__).parent / "_standalone_dst_do_not_edit"
TERMINAL_SCRIPTS_DST = Path(__file__).parent / "_terminal_scripts_dst_do_not_edit"
PATH_ARGS_SRC = Path(__file__).parent / "path_args"
IGNORE_DIRS = {"common", "__pycache__", "_terminal_scripts_dst_do_not_edit"}
IGNORE_FILES = {"setup.py", "__init__.py"}


def _iter_scripts():
    for src in sorted(DEV_HELPER.rglob("*")):
        if not src.is_file():
            continue
        if src.suffix != ".py":
            continue
        if src.name in IGNORE_FILES:
            continue
        rel = src.relative_to(DEV_HELPER)
        if any(part in IGNORE_DIRS for part in rel.parts):
            continue
        yield rel


def _apply_patches(source: str, patches: dict[str, str]) -> str:
    for key, value in patches.items():
        source = re.sub(
            rf"^({re.escape(key)}\s*=\s*).*",
            rf"\g<1>{value}",
            source,
            flags=re.MULTILINE,
        )
    return source


_SETTINGS_RE = re.compile(
    r'^(?P<lead>\s*)# === SETTINGS START ==='
    r'(?P<body>.*?)'
    r'(?P=lead)# === SETTINGS END ===(?:\n|$)',
    re.DOTALL | re.MULTILINE,
)


def _reposition_settings(content: str) -> str:
    match = _SETTINGS_RE.search(content)
    if match:
        block = textwrap.dedent(match.group(0))
        block = block.rstrip("\n") + "\n\n"
        content = content[:match.start()] + content[match.end():]

    lines = content.splitlines(keepends=True)
    future_lines = []
    non_future_lines = []
    for line in lines:
        if (
            line.strip().startswith("from __future__ import")
            and "__stickytape_write_module" not in line
        ):
            future_lines.append(line.lstrip())
        else:
            non_future_lines.append(line)

    insert_pos = 0
    for i, line in enumerate(non_future_lines):
        if line.startswith("#!"):
            insert_pos = i + 1
            break

    for i in range(insert_pos, len(non_future_lines)):
        if non_future_lines[i].strip():
            insert_pos = i
            break

    prefix = (
        non_future_lines[:insert_pos]
        + future_lines
        + ["\n"]
        + ([block + "\n"] if match else [])
    )
    return "".join(prefix + non_future_lines[insert_pos:])


class ScriptBuilder:
    _WORKFLOW_FILE_RE = re.compile(
        r"^(?P<lead>\s*)WORKFLOW_FILE\s*=\s*(?P<quote>['\"])(?P<path>[^'\"]+)(?P=quote)",
        re.MULTILINE,
    )

    def __init__(self, src_rel_path: Path, dst_rel_path: Path, patches: dict[str, str] | None = None):
        self.src_rel_path = src_rel_path
        self.dst_rel_path = dst_rel_path
        self.patches = patches or {}

    @property
    def module_path(self) -> str:
        return self.src_rel_path.with_suffix("").as_posix().replace("/", ".")

    @property
    def terminal_name(self) -> str:
        return self.dst_rel_path.name

    def _load_source(self) -> str:
        src_path = DEV_HELPER / self.src_rel_path
        return src_path.read_text(encoding="utf-8")

    def _find_workflow_file(self) -> Path | None:
        source = self._load_source()
        match = self._WORKFLOW_FILE_RE.search(source)
        if match:
            workflow_rel = match.group("path")
            if Path(workflow_rel).is_absolute():
                return Path(workflow_rel)
            return DEV_HELPER / self.src_rel_path.parent / Path(workflow_rel)
        return None

    def _copy_workflow_to(self, dst_root: Path, for_terminal: bool = False) -> None:
        workflow_src = self._find_workflow_file()
        if workflow_src and workflow_src.exists():
            if for_terminal:
                workflow_dst = dst_root / workflow_src.name
            else:
                workflow_dst = dst_root / self.dst_rel_path.parent / workflow_src.name
            workflow_dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(workflow_src, workflow_dst)
            print(f"  copied: {workflow_dst.relative_to(dst_root.parent)}")

    def bundle(self) -> None:
        source = self._load_source()
        if self.patches:
            source = _apply_patches(source, self.patches)

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False, encoding="utf-8"
        ) as tmp:
            tmp.write(source)
            tmp_path = tmp.name

        try:
            output = stickytape.script(
                tmp_path,
                add_python_paths=[str(PATH_ARGS_SRC), str(DEV_HELPER.parent)],
            )
        finally:
            Path(tmp_path).unlink()

        output = _reposition_settings(output)
        dst_path = STANDALONE / self.dst_rel_path
        dst_path.parent.mkdir(parents=True, exist_ok=True)
        dst_path.write_text(output, encoding="utf-8", newline="\n")
        print(f"  bundled: {dst_path.relative_to(STANDALONE)}")

        self._copy_workflow_to(STANDALONE)

    def write_terminal_wrapper(self) -> None:
        alias = "mod"
        lines = [
            "#!/usr/bin/env python3",
            "",
        ]
        if self.patches:
            lines.append(f'"""Wrapper: {self.terminal_name} with preset configuration."""')
        else:
            lines.append(f'"""Terminal wrapper for {self.terminal_name}."""')

        lines.extend([
            "",
            "def main():",
            f"    import dev_helper.{self.module_path} as {alias}",
        ])
        for key, value in self.patches.items():
            lines.append(f"    {alias}.{key} = {value}")

        _mb_bytes = {
            "SMALL_FILE_THRESHOLD_MB": "SMALL_FILE_THRESHOLD_BYTES",
            "BIG_FILE_THRESHOLD_MB": "BIG_FILE_THRESHOLD_BYTES",
        }
        for mb_key, bytes_key in _mb_bytes.items():
            if mb_key in self.patches:
                lines.append(
                    f"    {alias}.{bytes_key} = int({alias}.{mb_key} * 1024 * 1024)"
                )

        lines.extend([
            f"    try:",
            f"        {alias}.main()",
            f"    except AttributeError:",
            f"        {alias}.concatenate_files()",
            "",
            'if __name__ == "__main__":',
            "    main()",
        ])

        dst = TERMINAL_SCRIPTS_DST / self.terminal_name
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"  wrapper: {dst.relative_to(TERMINAL_SCRIPTS_DST.parent)}")

        self._copy_workflow_to(TERMINAL_SCRIPTS_DST, for_terminal=True)


def build_all() -> None:
    import importlib.util
    spec = importlib.util.spec_from_file_location("build_more", Path(__file__).parent / "build_more.py")
    build_more = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(build_more)
    SETTINGS = build_more.SETTINGS

    _INSTRUCTIONS = TERMINAL_SCRIPTS_DST / "! firstly pip install dev_helper"
    _instructions_backup = None
    if _INSTRUCTIONS.exists():
        _instructions_backup = _INSTRUCTIONS.read_text(encoding="utf-8")

    if STANDALONE.exists():
        shutil.rmtree(STANDALONE)
    STANDALONE.mkdir(parents=True)

    if TERMINAL_SCRIPTS_DST.exists():
        shutil.rmtree(TERMINAL_SCRIPTS_DST)
    TERMINAL_SCRIPTS_DST.mkdir(parents=True)

    if _instructions_backup:
        _INSTRUCTIONS.write_text(_instructions_backup, encoding="utf-8")

    base_scripts = list(_iter_scripts())
    count = 0

    for rel in base_scripts:
        builder = ScriptBuilder(rel, Path(rel))
        builder.bundle()
        builder.write_terminal_wrapper()
        count += 1

    for dest_name, bases in SETTINGS.items():
        for base_name, patches in bases.items():
            base_path = Path(base_name)
            dest_path = Path(dest_name)
            if dest_path.parent == Path("."):
                dest_path = base_path.parent / dest_path.name
            builder = ScriptBuilder(base_path, dest_path, patches)
            builder.bundle()
            builder.write_terminal_wrapper()
            count += 1

    print(f"\ndone: {count} file(s) written to {STANDALONE}/ and {TERMINAL_SCRIPTS_DST}/")


if __name__ == "__main__":
    build_all()